version: '3.5'

services: 
  example-backend:
    build: ./example-backend
    ports:
      - 8080:8080
    environment: 
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      #- POSTGRES_USER=postgres
      #- POSTGRES_PASSWORD=postgres
      #- POSTGRES_DATABASE=postgres

  example-frontend:
    build: ./example-frontend
    ports: 
      - 5000:5000

  redis:
    image: redis
  postgres:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres

